### ISSUE TITLE
Commands drawn from history cannot be executed.

### ISSUE THREAD

**Issue by yrammos** [marlonrichert/zsh-hist#10]
Reproduction:

```zsh
$ cd "$(mktemp -d)"
$ zsh -f
$ source /absolute/path/to/zsh-hist/zsh-hist.plugin.zsh
$ echo Test1
```
Press <kbd>↑</kbd><kbd>Enter</kbd>.

Expected result: `echo Test1` should be retrieved from the command history, then executed.
Actual result: `echo Test1` is retrieved from history, but it appears as if only a blank line was executed.

**Comment by Gerrit-K** [comment]
Not sure if that's the same issue, but I believe it is: when I open a new shell (/ tmux pane), the first command drawn from the history executes nicely, but after that, every time I want to execute a command from the history, after pressing enter the prompt gets cleared and nothing is executed. I only experience this on 89bf585 (latest master), but not on f29b320 (the parent commit).

**Comment by yrammos** [comment]
It sounds like the same issue, and I share your hunch that the latest master only is to blame. (I say "hunch" not having bisected the history.)

**Comment by marlonrichert** [comment]
Fixed.
