### ISSUE TITLE
Select multiple history entries

### ISSUE THREAD

**Issue by dasebasto** [marlonrichert/zsh-hist#13]
Very nice plugin, thanks!

I'd like to delete ranges of command lines from the history.

The use case is that it usually takes a lot of trial and error before building the perfect complex one-liner (e.g. a text processing command with regex). I want to keep the good command in history and delete the incorrect tentatives.

Python slice notation syntax could be convenient:

e.g:
```zsh
hist d [-3:]    # delete last 3 lines
hist d [-10:-2]   # delete last 10 lines, except the most recent one
hist d [1500:1510]   # delete lines with index 1500 to 1510
```

Maybe brackets can be omitted for an even more concise syntax.

Another suggestion, with probably less potential for popularity, but which would be practical in many cases:
```zsh
hist d 60m # delete all commands from the last 60 minutes
```

**Comment by marlonrichert** [comment]
While I love Python and it slice syntax, I don’t think it’s suitable for a shell command. I might implement it like this:
```zsh
hist d -1 -3     # delete last 3 lines
hist d -2 -10    # delete last 10 lines, except the most recent one
hist d 1500 1510 # delete lines with index 1500 to 1510
```

**Comment by marlonrichert** [comment]
It's there now! `hist` now accepts any number of selection arguments. So, to specify a range, just use normal `zsh` brace notation:
```zsh
hist d -{1..3}       # delete last 3 lines
hist d -{10..2}      # delete last 10 lines, except the most recent one
hist d {1500..1510}  # delete lines with index 1500 to 1510
```

**Comment by marlonrichert** [comment]
PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert).
