### ISSUE TITLE
Regex `\b` replaced with `^H` in multi-line command

### ISSUE THREAD

**Issue by owst** [marlonrichert/zsh-hist#20]
## Describe the bug

When I type out a multi-line command involving a regex `\b` character, the expansion replaces `\b` with `^H`.

## Steps To Reproduce
N.b. paste the first line first, then the remaining lines (to simulate typing out the command interactively).

```zsh
for f in $(grep -l '\bfoo\b' *); do
  echo "foo found in $f"
done
```
after pressing enter after `done` the prompt displays
```zsh
for f in $(grep -l '^Hfoo^H' *)
do
        echo "foo found in $f"
done
```

## Expected behavior
`\b` to be unchanged

## Observed behavior

`\b` was replaced with `^H` (which breaks the `grep` pattern)

## Environment:
 - OS: macOS Version 13.2.1 
 - Terminal: iTerm2 3.4.19
 - Zsh version: 5.8.1
 - Repo version: `6b0e5e6`

**Comment by owst** [comment]
Thanks @marlonrichert 👍

**Comment by marlonrichert** [comment]
No problem! 🙂 

PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 💝
