### ISSUE TITLE
The term "undo" is used twice

### ISSUE THREAD

**Issue by hlascelles** [marlonrichert/zsh-hist#3]
Great plugin - `undo` is exactly what I want to use it for (the `^_` version).

However I see from the instructions that `hist u` is also an "undo". I have now finally got it but I did find it confusing. Maybe change that one to be "rollback" (with letter `b`) or "revert" (with letter `v`)?

**Comment by marlonrichert** [comment]
Hm, good point. Thanks for the feedback. I’ll have to think about it.

**Comment by marlonrichert** [comment]
I have considered the options, but I still think `undo` is the most clear in this context. You wouldn't expect `delete`, `edit`, `fix` and `get` to mean the same thing in different contexts either, would you?

Although, I do like `rollback` and `revert` for this, but if I use those, I don't want those to be `b` or `v`. That is too hard to remember. Then I would just like it to be `r`, but that then leaves the question: What would then be the new name for `reload`?

One other option could be to rename `undo` to `abort` and use `a` for it. 🤔

**Comment by marlonrichert** [comment]
Note, by the way, that just as with other Undo features, you can execute `hist u` multiple times to go further and further back. So, in that sense, too, `undo` feels more appropriate to me than `revert` or `roll back`.

**Comment by hlascelles** [comment]
Yes, I see what you mean. I'll leave it with you... I am only using the `hist d` and `^_` functionality (a lot!), so you choose. I just thought you'd like to hear a newcomer's perspective :+1:.
