### ISSUE TITLE
Widgets are not found anymore

### ISSUE THREAD

**Issue by Gerrit-K** [marlonrichert/zsh-hist#4]
I'm loading zsh-hist using [`zinit`](https://github.com/zdharma/zinit) and sice the [latest commit](https://github.com/marlonrichert/zsh-hist/commit/81b06347af3331d57aa218a4929f623788728d83) I get an error whenever I want to execute a zle widget. For example: ``No such shell function `.hist.undo.widget'`` for `^_`. Probably related to the removed autoload stuff?

**Comment by marlonrichert** [comment]
Thanks for reporting this. This is actually [a bug in Zinit](https://github.com/zdharma/zinit/issues/441), but I can add a workaround for it, since [it can take many months before such a bug in Zinit gets fixed](https://github.com/zdharma/zinit/issues/366).

**Comment by marlonrichert** [comment]
PS: If you're interested in switching to a less buggy plugin manager that functions more transparently, I can highly recommend [Znap](https://github.com/marlonrichert/zsh-snap). 😉

**Comment by Gerrit-K** [comment]
Thanks for the quick reply! I honestly didn't think of that, sorry. If it doesn't take too much time, I'd appreciate a workaround, but I would truly understand if you don't want to integrate workarounds for external bugs.

Thanks for the hint on Znap, will take a look 🙂  I originally used oh-my-zsh, then zplug and eventually zinit due to the freedom and configurability it offers (i.e. I also manage a couple of binary releases, such as k3d, pulumi and terraform, with it). But I have to agree that due to the complexity a fix on one end often causes new bugs on others and it also makes it more difficult for potential contributors to understand the project and support the maintainer ...

**Comment by marlonrichert** [comment]
No problem: Here's the workaround already. 🙂

And if there's any features you'd like to see in Znap to help you switch over, feel free to open issues for them over there.
