### ISSUE TITLE
Code formatting ignores HIST_IGNORE_SPACE

### ISSUE THREAD

**Issue by Gerrit-K** [marlonrichert/zsh-hist#6]
I have the (arguably bad?) habit of prefixing commands I don't want to have in my history (e.g. because of temporary, specific parameters or sensitive arguments) with a space. For that I have `setopt hist_ignore_space` in my `.zshrc`. 

Unfortunately the new code formatting feature (which sounds great, btw) doesn't respect that option. I tried with and without `HIST_REDUCE_BLANKS` but the results are the same: the leading whitespace is removed and thus the command is saved in history.

It would be great if the formatting would respect that setting (e.g. by keeping leading whitespace?) or (as a workaround) if the formatting could be disabled.

**Comment by marlonrichert** [comment]
Sure, I could make it respect that setting. Thanks for bringing it up.

**Comment by marlonrichert** [comment]
Fixed.

**Comment by Gerrit-K** [comment]
Awesome! Thanks for the quick fix :rocket:
